<h2><b>NumPy</b></h2><br>
Numpy is the core library for scientific computing in Python. It provides a high performance multidimensional array object, and tools for working with these arrays.

In [1]:
import numpy as np

<h3><b>Arrays</b></h3><br>
indexed by tuple of non-negative numbers<br>
The rank of the array is the number of dimensions, and the shape of an array is a tuple of numbers giving size of the array along each dimension.

In [2]:
# create a rank 1 array
a = np.array([0,1,2])
print(type(a))

# this will print the dimension of the array
print(a.shape)
print(a[0])
print(a[1])
print(a[2])

# change an element of the array
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]


In [3]:
# create rank 2 array
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0,0],b[0,1],b[1,0])

(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [4]:
print(b.shape)

(2, 3)


<h3><b>Creating NumPy array</b></h3><br>
NumPy also provides many in-built fun to create arrays.

In [5]:
# create a 3x3 array of all 0's
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#create a 2x2 of all 1's
b = np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [7]:
#create a 3x3 constant array
c = np.full((3,3), 8)
print(c)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [8]:
# create 3x3 array with random values
d = np.random.random((3,3))
print(d)

[[0.25726029 0.1790852  0.74485692]
 [0.19812711 0.78874511 0.13577853]
 [0.75357019 0.2646377  0.11349948]]


In [9]:
#create a 3x3 identity matrix
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#convert list to array
f = np.array([2,3,1,0])
print(f)

[2 3 1 0]


In [11]:
# arrange() will create arrays with regularly incrementing values
g = np.arange(20)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
#note mix of tuple and lists
h = np.array([[0,1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)

[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]


In [13]:
# create an array of range with float data type
i = np.arange(1, 8, dtype = np.float)
print(i)

[1. 2. 3. 4. 5. 6. 7.]


In [14]:
#linspace() will create arrays with specified number
j = np.linspace(2, 4, 5)
print(j)

[2.  2.5 3.  3.5 4. ]


In [15]:
k = np.indices((2,2))
print(k)

[[[0 0]
  [1 1]]

 [[0 1]
  [0 1]]]


In [16]:
k = np.indices((3,2))
print(k)

[[[0 0]
  [1 1]
  [2 2]]

 [[0 1]
  [0 1]
  [0 1]]]


In [17]:
#used to return arrays which can be used
k = np.indices((3,3))
print(k)

[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


<h3><b>Datatypes</b></h3>

In [18]:
# let numpy choose the datatype
x = np.array([0, 1])
y = np.array([2.0, 3.0])

#force a particular datatype
z = np.array

<h3><b>Array Indexing</b></h3><br>
1)Field Access

In [19]:
import numpy as np
x = np.zeros((3,3), dtype = [('a' , np.int32), ('b' , np.float64 , (3,3))])

In [20]:
x

array([[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])],
       [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])],
       [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]],
      dtype=[('a', '<i4'), ('b', '<f8', (3, 3))])

In [21]:
print(x['a'].shape)

(3, 3)


In [22]:
x['a'].dtype

dtype('int32')

In [23]:
x['b'].shape

(3, 3, 3, 3)

In [24]:
x['b'].dtype

dtype('float64')

<h3><b>Basic Slicing </b></h3>

In [25]:
x = np.array([5, 6, 7, 8, 9])
x[1:7:2]

array([6, 8])

In [26]:
x[-2:5]

array([8, 9])

In [27]:
x[-1:1:-1]

array([9, 8, 7])

In [28]:
x[-5:-1:-2]

array([], dtype=int32)

In [29]:
x[-5:-1]

array([5, 6, 7, 8])

In [30]:
x[-5:-1:-1]

array([], dtype=int32)

In [31]:
x[-1:-5:-1]

array([9, 8, 7, 6])

In [32]:
y = np.array([ [[0],[1],[2],[3]], [[4],[5],[6]], [7]])
y.shape

(3,)

In [33]:
y[1:3]

array([list([[4], [5], [6]]), list([7])], dtype=object)

In [34]:
a = np.array([[5,6,7,8], [1,2,3,4], [9,10,11,12]])
a[:2, 1:3]
b

array([[1., 1.],
       [1., 1.]])

In [35]:
a = np.array([[5,6,7,8], [1,2,3,4], [9,10,11,12]])
a

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [36]:
#access the middle row
row1 = a[1, :] #rank 1 view of second row of a
row2 = a[1:2, :] #rank 2 view of second row of a
row3 = a[[1], :] #rank 3 view of second row of a
print(row1,row1.shape)
print(row2,row2.shape)
print(row3,row3.shape)

[1 2 3 4] (4,)
[[1 2 3 4]] (1, 4)
[[1 2 3 4]] (1, 4)


In [37]:
col_r1 = a[: , 1]
col_r2 = a[:, 1:2]
print(col_r1,col_r1.shape)
print(col_r2,col_r2.shape)

[ 6  2 10] (3,)
[[ 6]
 [ 2]
 [10]] (3, 1)


<h3><b>Advanced Indexing </b></h3>

In [38]:
a = np.array([[1,2], [3, 4], [5, 6]])
# Find the elements of a that are bigger than 2
print (a > 2)  

# to get the actual value
print (a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [41]:
a = np.array([[1,2], [3, 4]])

# An example of integer array indexing.
# The returned array will have shape (2,) and 
print (a[[0, 1], [0, 1]])

# The above example of integer array indexing is equivalent to this:
print (np.array([a[0, 0], a[1, 1]]))

[1 4]
[1 4]


In [42]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print( a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print (np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


<h3><b>Array math</b></h3>

Basic mathematical functions are available as operator and also as functions in NumPy. It operates elementwise on array.

In [45]:
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([[7,8],[9,10],[11,12]])

# Elementwise sum; both produce the array
print (x + y)
print (np.add(x, y))

[[ 8 10]
 [12 14]
 [16 18]]
[[ 8 10]
 [12 14]
 [16 18]]


In [47]:
# Elementwise difference; both produce the array
print( x - y)
print( np.subtract(x, y))

[[-6 -6]
 [-6 -6]
 [-6 -6]]
[[-6 -6]
 [-6 -6]
 [-6 -6]]


In [48]:
# Elementwise product; both produce the array
print (x * y)
print( np.multiply(x, y))

[[ 7 16]
 [27 40]
 [55 72]]
[[ 7 16]
 [27 40]
 [55 72]]


In [49]:
# Elementwise division; both produce the array
print( x / y)
print (np.divide(x, y))

[[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]
[[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]


In [50]:
# Elementwise square root; produces the array
print (np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


We can use "dot" function to calculate inner products of vectors or to multiply matrices or multiply vector by matrix

In [52]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

a = np.array([9,10])
b = np.array([11, 12])

# Inner product of vectors; both produce 219
print (a.dot(b))
print (np.dot(a, b))

219
219


In [53]:
# Matrix / matrix product; both produce the rank 2 array
print( x.dot(y))
print (np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays, one of the most useful is sum:

In [54]:
x = np.array([[1,2],[3,4]])

# Compute sum of all elements
print( np.sum(x))  
# Compute sum of each column
print( np.sum(x, axis=0))  
# Compute sum of each row
print( np.sum(x, axis=1))

10
[4 6]
[3 7]



Transpose is one of the common operation often performed on matrix, which can be achieved using T attribute of an array object.

In [55]:
print (x)
print (x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [56]:
v = np.array([1,2,3])
print (v )
print (v.T)

[1 2 3]
[1 2 3]


<h3><b>Broadcasting</b></h3>

Broadcasting enables arithmetic operations to be performed between different shaped arrays. Adding a constant vector to each row of matrix.

In [57]:
# create a matrix
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
# create a vector
v = np.array([1, 0, 1])

# Create an empty matrix with the same shape as a
b = np.empty_like(a)   

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(3):
    b[i, :] = a[i, :] + v

print (b)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


Performing the above operation on a large matrix through loop in Python could be slow. Alternative approach.

In [58]:
# Stack 3 copies of v on top of each other
vv = np.tile(v, (3, 1))  
print (vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]]


In [59]:
# Add x and vv elementwise
b = a + vv  
print (b)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v

In [60]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1, 0, 1])

# Add v to each row of a using broadcasting
b = a + v  
print (b)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


Let's look at some applications of broadcasting:

In [61]:
# Compute outer product of vectors
# v has shape (3,)
v = np.array([1,2,3])
# w has shape (2,)
w = np.array([4,5]) 
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print (np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [62]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3)

print (x + v)

[[2 4 6]
 [5 7 9]]


In [63]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column

print( (x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [64]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print (x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [65]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print( x * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [66]:
import numpy as np
python_list=[2,6,5,3,1]
np.delete(python_list,1)

array([2, 5, 3, 1])

In [67]:
arr=np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [68]:
np.reshape(arr,(8,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [69]:
np.reshape(arr,(12,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

Broadcasting typically makes code more concise and faster.